export { getHome } from "./home";
export { getStats } from "./stats";
export { getTeams } from "./teams";
export { getHonours } from "./honours";
export { getNextFixture } from "./fixtures";
export { getContact } from "./contact";
export { getNews, getNewsBySlug, getNewsSlugs } from "./news";
export { getSponsors } from "./sponsors";
export { getCoaches } from "./coaches";
export { getGalleries, getGalleryBySlug, getGallerySlugs } from "./gallery";
export type { Team } from "./teams";
export type { Honour } from "./honours";
export type { NewsItem, NewsPost } from "./news";
export type { Fixture } from "./fixtures";
export type { Contact } from "./contact";
export type { Coach } from "./coaches";
export type { Gallery } from "./gallery";
export type { Sponsor } from "./sponsors";
export type { Medal, Photo } from "./types";